/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as R404Import } from './routes/_404'
import { Route as IndexImport } from './routes/index'
import { Route as DocumentationIndexImport } from './routes/documentation/index'
import { Route as DemoIndexImport } from './routes/demo/index'

// Create/Update Routes

const R404Route = R404Import.update({
  id: '/_404',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentationIndexRoute = DocumentationIndexImport.update({
  id: '/documentation/',
  path: '/documentation/',
  getParentRoute: () => rootRoute,
} as any)

const DemoIndexRoute = DemoIndexImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_404': {
      id: '/_404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoIndexImport
      parentRoute: typeof rootRoute
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof R404Route
  '/demo': typeof DemoIndexRoute
  '/documentation': typeof DocumentationIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof R404Route
  '/demo': typeof DemoIndexRoute
  '/documentation': typeof DocumentationIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_404': typeof R404Route
  '/demo/': typeof DemoIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/demo' | '/documentation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/demo' | '/documentation'
  id: '__root__' | '/' | '/_404' | '/demo/' | '/documentation/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DemoIndexRoute: typeof DemoIndexRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DemoIndexRoute: DemoIndexRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_404",
        "/demo/",
        "/documentation/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_404": {
      "filePath": "_404.tsx"
    },
    "/demo/": {
      "filePath": "demo/index.tsx"
    },
    "/documentation/": {
      "filePath": "documentation/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
